# Generated by Django 4.2.10 on 2024-02-15 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashpw', models.TextField()),
                ('fullname', models.TextField(max_length=512)),
                ('dob', models.DateField(null=True, verbose_name='date of birth')),
                ('gender', models.BooleanField()),
                ('role', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
