# Generated by Django 4.2.10 on 2024-03-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("tourist_id", models.ImageField(upload_to="")),
                ("time", models.IntegerField(default=0)),
                ("last_view", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(unique=True)),
                ("key", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Tourist",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("special", models.TextField()),
                ("area", models.TextField()),
                ("address", models.TextField()),
                ("info", models.TextField()),
                ("url_imgs", models.TextField()),
                ("time_visit", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("hashpw", models.TextField()),
                ("fullname", models.TextField(max_length=50)),
                ("dob", models.DateField(null=True, verbose_name="date of birth")),
                ("gender", models.SmallIntegerField(default=0)),
                ("role", models.TextField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
